# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e4d13eab7552fe1b4c93f58d4a41c404af7351bc378b56eb659f653b284339c554e6a127b7e063b1469b1c97e80d168cf3d1c87156f845ffb655b3677c53ff1

test:
  secret_key_base: fcfb5fcf91f6eaf633fcada66e547863701bb8c30115b0817fa2eec16fb3d45b0785c10e897ac2fad528c0a9f6639d021548015cbe56adcf616a499f0a6041ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
